name: Build and release ruby gem

on:
  pull_request:
    branches: [ master ]
  push:

jobs:
  build-release-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --quiet --default-toolchain=1.73.0 --profile=minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Compile dependencies
        run: bundle exec rake compile
      - name: Test
        run: bundle exec rake spec
